{
 "title": "Carbonara Insight",
 "description": "Provides Carbonara metrics for tasks",
 "tags": [
  "carbonara",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cloudprovider", "query": "AWS" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace!=\"carbonara-monitoring\"}, namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", container =\"$container\"}, pod)"
    }
   },
   {
    "name": "resource_location",
    "query": {
     "query": "label_values(carbonara_runner_moer_score{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}, metric_location)"
    }
   },
   {
    "name": "current_location",
    "query": {
     "query": "label_values(carbonara_runner_moer_score{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\"}, current_node_location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lifetime Carbon Consumption (Tons)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(carbonara_runner_carbon_from_compute{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}[100y]))"
    }
   ]
  },
  {
   "title": "MOER [lbs/MWh]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "carbonara_runner_moer_score{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "MOER Score"
    }
   ]
  },
  {
   "title": "Node CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"POD\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[5m])) / scalar(avg(avg_over_time(machine_cpu_cores{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"kube-system\"}[5m]))))",
     "legendFormat": "CPU Usage - {{ node }} "
    }
   ]
  },
  {
   "title": "Carbonara Runner From Compute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "tonnes" } },
   "targets": [
    {
     "expr": "carbonara_runner_carbon_from_compute{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "KwH From Compute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "carbonara_runner_kwh_compute{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Read + Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_working_set_bytes{container!=\"POD\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\", namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Carbonara Runner From Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "tonnes" } },
   "targets": [
    {
     "expr": "carbonara_runner_carbon_from_memory{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "KwH From Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "carbonara_runner_kwh_memory{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "Storage (Disk IO)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{container!=\"POD\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device!=\"\", image!=\"\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "FS Usage"
    }
   ]
  },
  {
   "title": "Carbonara Runner From Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "tonnes" } },
   "targets": [
    {
     "expr": "carbonara_runner_carbon_from_storage{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "KwH From Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "carbonara_runner_kwh_storage{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(increase(node_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[5m])) by (instance)",
     "legendFormat": "Network Receive Bytes - {{ instance }}"
    }
   ]
  },
  {
   "title": "Carbonara Runner From Network (In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "tonnes" } },
   "targets": [
    {
     "expr": "carbonara_runner_carbon_from_network_in{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "KwH From Network (In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "carbonara_runner_kwh_network_in{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(increase(node_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[5m])) by (instance)",
     "legendFormat": "Network Transmit Bytes - {{ instance }}"
    }
   ]
  },
  {
   "title": "Carbonara Runner From Network (Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "tonnes" } },
   "targets": [
    {
     "expr": "carbonara_runner_carbon_from_network_out{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  },
  {
   "title": "KwH From Network (Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "carbonara_runner_kwh_network_out{cloud_provider=\"$cloudprovider\", instance=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", metric_location=~\"$resource_location\"}",
     "legendFormat": "Runner - {{ container }}"
    }
   ]
  }
 ]
}